<?php

 /**
  * @var \Magento\Framework\Escaper $escaper
  */
?>
 <script src="https://cdn.jsdelivr.net/npm/uuid4@2.0.3/browser.min.js"></script>
<div class="search-main">
    <input type="text" 
           placeholder="<?= $escaper->escapeHtmlAttr(__('search here...')) ?>" 
           id="searchbox" class="searchbox" />
    <div id="search-component" data-bind="scope:'searchcomponent'">
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
        {
            "#search-component": {
                "Magento_Ui/js/core/app": {
                "components": {
                        "searchcomponent": {
                            "component": "Thecommerceshop_Predictivesearch/js/searchAutocomplete"
                        }
                    }
                }
            }
        }
        </script>
    </div>
</div>