<?php
/**
 *
 * @package Ceymox_TypesenseSearch
 * @author Ceymox Technologies Pvt. Ltd.
 */

 /**
  * @var \Magento\Framework\Escaper $escaper
  */
  $viewModel = $block->getData('view_model');
?>
<div id="refine-toggle" class="visible-xs visible-sm">+ Refine</div>
<div class="filter_main hidden-sm hidden-xs">
    <div id="selected-filter">
        <button id="clear_all"><?= $escaper->escapeHtmlAttr(__('Clear All')) ?></button>
        <div id="filter-items"></div>
    </div>
    <?php if ($viewModel->priceSlider() == 1): ?>
        <span class="item_label"><?= $escaper->escapeHtmlAttr(__('Price')) ?></span>
        <div class="slider-box">
            <div id="price-range" class="slider"></div>
           <input type="text" id="priceRange" readonly> 
           
        </div>
    <?php endif; ?>
     <div class="container hidden-sm hidden-xs" id="filter_container"> 
        <div class="filter_main_test" id="price"></div>
    </div>
   
    </div>
</div>
